### ISSUE TITLE
HTML-Interface does not work (any more?)) when speech (en:Marvin) is on

### ISSUE THREAD

**Issue by Laterunner** [jromang/picochess#144]
Hi, I think I found a bug in V 0.55:
when I start a game and play picochess with "computer-voice = en:Marvin" the moves are spoken but often NOT displayed on the HTML-interface. In many cases the moves appear AFTER the player made his next move.

I tried out a different voice (Elsie), I even changed Elsie's setting to 450 words per minute => The moves are not displayed immediately.

When computer voice is deactivated (commented out in picochess.ini). The moves are displayed correctly on the HTML-Interface.

I think the speech feature is one of picochess best features. Marvin is a clear voice (Elsie is much worse). In fact voice output is one of main reason's why I use picochess. With voice activated you do not need do watch the screen or the clock. However the HTML-Display should of course also work when voice is on....

Do you have an idea why voice output interferes with HTML output?
Is there a quick fix? Maybe different timing of output to the HTML interface (after speech has finished)

I use the Odroid XU4. Sound output is via USB Audio to a speaker (good, powerful sound)
My DGT-Board is BT connected to BT. I also tried USB connection with BT off (-> same Bug). Clock is DGT3000 . Picochess 0.55.

BTW there is still a typo in picochess.ini.example. It should say games.pgn not games .png (probably no need for a correction)

Kind regards
Laterunner

**Comment by pablo2000** [comment]
Dang it! Thought I nailed that one. I'll look at it right now.

Have corrected picochess.ini.example - thanks.

**Comment by LocutusOfPenguin** [comment]
even pgn is one year older as png, i still make this error.
In my heart I seem to be a drawer artist, not a chess one ;-)

Please continue posting found errors, no matter how big they are..bug is bug. Thanks!
After all we all make the picochess world abit brighter.

BTW. i would like the speech in my language - and alot quicker (to finish) for example in short notation.

**Comment by pablo2000** [comment]
OK.. the speech/web interaction has been fixed - testing welcome, but my testing seems solid.

P

**Comment by pablo2000** [comment]
Jurgen

I didn't close this issue, but it is reported as closed.... have you enabled auto-close based on commit??

**Comment by LocutusOfPenguin** [comment]
its closed by github, when y use - for example -  "fix" in your comment.

**Comment by pablo2000** [comment]
Aha...did not know that - we live and learn!

**Comment by Laterunner** [comment]
wow that was a quick answer. will check this as soon as possible. No I did not close the commit. I am new to this (git) BTW artist are nice persons :)

**Comment by Laterunner** [comment]
ok - working now :) thank you

**Comment by LocutusOfPenguin** [comment]
If we ever have a german speech, y can also learn that Läufer = bishop , is not pronounced like "Laufer" (but i know, you don't use speech either).
So my name should be written with "ue", and not "u", as long y don't have this special chars.

**Comment by pablo2000** [comment]
@Laterunner - pleasure. Keep the bug reports coming. You should be aware that, partly because of how it works, and partly because of the time it takes to 'say' the move, the speech will always be a little behind the web or clock (web is fastest to update), especially for book moves. That could be an issue if you are playing a short Blitz time control - you might find you lose two or three seconds per move if you are just waiting for speech. Less of a problem on long time controls or Fischer. Just a point to consider.

@Jurgen - Not as an immediate matter, but I will have a think about user programmable vocabulary for the speech. Could be difficult though as it uses text-to-speech and I'm not familiar with that for non-english languages, but I agree it would be a really nice thing to have.

**Comment by jurgen** [comment]
Why I am I getting this email? I am Jurgen, but inform you I am not that
Jurgen you need.

Jurgen

**Comment by pablo2000** [comment]
Apologies, didn't know we had more than one here (obvious really I suppose) - was just too lazy to type full name of LocutusOfPenguin. Please ignore.

Also, apologies to LocutusOfPenguin for mis-spelling Jürgen.

It seems to be a day of apologies - oh well.

**Comment by LocutusOfPenguin** [comment]
@pablo2000 
Im not too happy with these keys => Also i prefer it be more like the dgt standard so not "mov 5" and for sure not use this as a key.
The whole speech is - concerning me - a refactor candidate.
I was abit supprised @Laterunner likes it so much.

No problem. If i were non-german i would also leave away this two points. But it changes the sound completely (but y cant know it!).

My apologies also for misusing the english grammer. Perhaps google can release a doodle for saying sorry today.

**Comment by jurgen** [comment]
Well, if you meant me, the Jurgen without the umlaut was correct. :)

**Comment by pablo2000** [comment]
I'm not sure I understand what your first part of this message is saying. What is it that you're not happy with? <confused>. I have spent most of the day writing in Forth - so my brain is a bit backwards now.

I agree. The whole speech area works ok, but would benefit from refactoring. It's quite inefficient in both code and memory and should be reworked at some point.

As to my use of umlaut - I have to confess that I have no excuse for being lazy with it. I studied German in high school for quite a few years and I do know the importance for the sound. So I must apologise even more ;)

**Comment by jurgen** [comment]
But,

Can I be removed from this group?  ;-)

Thanks!

Jurgen

**Comment by LocutusOfPenguin** [comment]
jurgen:
I think its explained here:
https://help.github.com/articles/unsubscribing-from-conversations/

Pablo:
with "key usage" i mean something like starting line 116 from chesstalker.py
with "mov 5", i mean something like: the dgt modes 1-22 are equal clear as this text display in my eyes. To know what "f 3 2" means, y also have to learn it first (even it takes few secs).
I prefer it be same everywhere, and since dgt was before picochess why invent something new? dgt also able to display chars but they decided not to do so.

Both not that important for me...so, i never changed it.
