### ISSUE TITLE
Spurious Time Message on DGT 3000

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#161]
Spurious clock times appear very briefly on the DGT 3000 while playing a 3 second game (wQ on b6) against Stockfish:

http://youtu.be/QZdH_aurCnE

This error was not introduced with v0.58, but has been around for quite some time. It seems that the clock is having difficulties with the messages that the RPi2 throws at it.

**Comment by LocutusOfPenguin** [comment]
Hi dj,
i saw the video, but i cant get this reproduced. Can y always get this? If yes, how?
Do y have a log file ready when this happens?
Please use the newest version (now 0.58) from jromang master (i dont expect this a problem since you said that happens for long already - but i dont want to test alot of different versions).

Can y talk to me over skype, please? I have some hardware questions, y might help me (nothing with this issue!).
Jürgen

**Comment by djdekker** [comment]
Since this behaviour seems to be merely a cosmetic thing but nothing critical, i.e., it does not affect game play, I propose to close this issue.
