### ISSUE TITLE
Wrong move text for (IT) 15.c1b1

### ISSUE THREAD

**Issue by LocutusOfPenguin** [jromang/picochess#221]
Move 15:
Kb1 is displayed as "Tb1" instead of "Rb1" (italian language)

[picochess.txt](https://github.com/jromang/picochess/files/658119/picochess.txt)

All done on MY branch (see eMail from 16.Dez 17:41)

**Comment by Albireo54** [comment]
Hi Jürgen,

attached you will find the printouts of the 'git log' command.

I also play a game on the RPi3 (the previous one was played on the Linux Mint desktop PC), and I can confirm that all the white King moves are displayed as 'Txx' instead of 'Rxx' in italian language.

Luigi
![git_log](https://cloud.githubusercontent.com/assets/23236054/21282244/66a0a77a-c3f3-11e6-84d6-f1f53e6b7f9b.jpg)
