### ISSUE TITLE
Sound via GPIO (I2S)

### ISSUE THREAD

**Issue by Laterunner** [jromang/picochess#235]
Hi, 
my question is is about picochess and the GPIO Connector:
1. Do you think it is possible Is it possible to get output of Picochess voices via GPIO (I2S) and if so would it still be possible to have a direct connection DGT 3000 clock.

2. At the Moment I use a USB soundcard and a small amplifier + speaker to get  sound. Maybe one could replace this either by a HiFiBerryAMP or I cheaper I2S Amplifier. Do you think this is possible?

Thank you for reply

**Comment by lucasvdp** [comment]
Hi,

In principle instead of using I2S you could also configure pin GPIO12 and GPIO13 (rasp pin 32 and 33) as PWM by selecting ALT0. This way you transfer the analog signal that is normally on the jack plug to these two GPIO pins. Normally you would place an RC filter and diode protection in-between the GPIO pin and the headphone/amplifier/speaker but you might not even need all of these extra components.

Let me know it if works!

Regards,

Lucas


Van: Laterunner [mailto:notifications@github.com]
Verzonden: maandag 8 mei 2017 12:18
Aan: jromang/picochess <picochess@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [jromang/picochess] Sound via GPIO (I2S) (#235)


Hi,
my question is is about picochess and the GPIO Connector:

1.      Do you think it is possible Is it possible to get output of Picochess voices via GPIO (I2S) and if so would it still be possible to have a direct connection DGT 3000 clock.

2.      At the Moment I use a USB soundcard and a small amplifier + speaker to get sound. Maybe one could replace this either by a HiFiBerryAMP or I cheaper I2S Amplifier. Do you think this is possible?

Thank you for reply

**Comment by Laterunner** [comment]
ok, thank you for your reply, but directing the sound output from the jack to GPIO is no real advantage. I thought of connecting a DAC to the GPIO. You need only 5 connectors: i.e. Pin (40 Dout, 35 LRCLK, 12 BCK, GND and +V). On Jessie this works (speaker-test -c2 is o.k.). However I could not yet get a sound output with picochess voices.

A big drawback is: these connections interfere with the wired connection of the DGT3000 to the Pi´s GPIO (Pins 35, 3, 5, 12 and GND): No DGT3000Pi mode. 

Therefore when using I2s sound the GPIO cannot be use to generate the Display on the DGT3000. For this the slower Cable connection of the Dgt3000 to the BT Board has to be used.

Probably I stay with my USB Sound card output which fully works (even with DGT3000 directly wired to the Raspberry GPIOs)

Kind regards Laterunner
