### ISSUE TITLE
Turning on/off Picochess features via GUI

### ISSUE THREAD

**Issue by ifekali** [jromang/picochess#61]
Average users (non-computer-experts) are unable to edit /opt/picochess/picochess.ini, most notably to turn the latest speech capabilities on/off.

Asking for a solution to do it via GUI. A preferences page with simple on/off buttons maybe? Anybody with a good idea/proposal as how to do this?

**Comment by djdekker** [comment]
Perhaps this could be done with the spare white or black queen? This would be more user friendly than using a GUI, because a GUI needs a monitor being connected.

**Comment by ifekali** [comment]
Very good idea!

**Comment by LocutusOfPenguin** [comment]
Hi,
this issue is now 1year old, and i dont see any resources of a developer to do it.
Also i would like to exchange chesstalker (since there is issue #154 providing a better talking system).
Btw. even after menu refactor, there are only 3 queen places left out of 2x32=64.

This issue be closed very soon. Sorry.

**Comment by djdekker** [comment]
Ok.
