### ISSUE TITLE
Observe mode halts randomly

### ISSUE THREAD

**Issue by ifekali** [jromang/picochess#74]
Weird behaviour in observe mode. It will fail to display a move in middle of the game, sometimes halting, sometimes continuing with the game. If any piece is lifted and put back, it will start displaying countdown on the clock.

Here's a video of bug in action:

https://youtu.be/lhpKC4Bqh8E

-Izmet

**Comment by djdekker** [comment]
Please make sure which side is to move.
In your video you are playing 8. 0-0 immediately followed by 9. Nxg5 *without* any Black move in between. That is illegal and will not be accepted in observe mode. The same happens when you let White play g4 and then 0-0 without a Black move in between, and again when you let Black play Bb4 followed by 0-0 without a White move in between. These are illegal moves, which are clearly not accepted in observe mode.
On the other hand, the capture Qxd4 is in fact registered, but not displayed. That must be a bug.
Also, displaying thinking time in observe mode must be a bug.

**Comment by ifekali** [comment]
Shit, you are right of course. Anyway, I shot the video because I noticed the countdown bug and then run into the "halt" issue (now shown to be nonexistent).

I am closing this issue and reopening it with countdown bug only.

**Comment by ifekali** [comment]
Noted, issue closed and reopened with "lifting a piece starts countdown" bug. I was trying to report on this bug in the first place, but then got carelessly sidetracked with this nonexistent issue.


> On 20. maj 2015, at 10.22, DJ Dekker <notifications@github.com> wrote:
> 
> Please make sure which side is to move.

- 
Jonas Žnidaršič
jonas@jonas.si
